### ISSUE TITLE
Update README.md with extension and legal stuff

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas-content-engine#10]
A few things to consider:
→ Readme for every subfolder
→ Showing how it works from using a network graph
→ Create a repo template for others to use/ start their own data product
→ Monitoring the product issues/ bugs/ directly from the framework.

**Comment by jravenel** [comment]
cc @chicken-biryani

**Comment by FlorentLvr** [comment]
data product to be transformed and decomisionned (naas reset strategy)
