### ISSUE TITLE
When I connect to tools via button widget, I check if secret is already present, if not it opens an input to capture it 

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas-content-engine#6]
A first good step is to use the Linkedin function and ensure that the logic works : 
- if secret already exist then OK
- if secret do not exist ask for it, and add it to secrets

The input should appear below the connect button:
<img width="867" alt="Screenshot 2022-08-01 at 12 13 25" src="https://user-images.githubusercontent.com/21052349/182127068-c400735a-0b0c-44fa-93fd-c1722434a0d6.png">

Resources: 
https://stackoverflow.com/questions/61339771/ipywidgets-how-to-evaluate-answers-on-form

**Comment by FlorentLvr** [comment]
Integrated to master manually
